const DURATION_HIDE = 300;
const DURATION_ANIMATED = 300;
const BG_SUCCESS = '#2ecc71';
const BG_INFO = '#f6e58d';
const BG_ERROR = '#e74c3c';
const BG_WARN = '#f1c40f';
const BG_DEFAULT = '#fff';
const INITIAL_SNACKBAR = {
    FROM_POSITION: -200,
    DURATION: 1500
};

export {DURATION_HIDE, DURATION_ANIMATED, BG_SUCCESS, BG_INFO, BG_ERROR, BG_WARN, BG_DEFAULT, INITIAL_SNACKBAR};
